splash = false

wallpaper {
    monitor = DP-3
    path = /home/phsd/Pictures/Wallpapers/wallhaven-7p58gy.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = /home/phsd/Pictures/Wallpapers/wallhaven-7p58gy.png
    fit_mode = cover
}